# Generated by Django 5.1.1 on 2024-12-04 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0002_tahunakademik_semester_tahunakademik_tahun'),
    ]

    operations = [
        migrations.AddField(
            model_name='matakuliah',
            name='kode',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matakuliah',
            name='nama',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matakuliah',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='akademik.tahunakademik'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matakuliah',
            name='sks',
            field=models.IntegerField(default=14),
            preserve_default=False,
        ),
    ]
