# Generated by Django 5.1.1 on 2024-12-04 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0005_alter_jadwal_tahun_akademik'),
    ]

    operations = [
        migrations.AddField(
            model_name='krs',
            name='jadwal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='akademik.matakuliah'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='krs',
            name='mahasiswa',
            field=models.CharField(default='budi', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='krs',
            name='tahun_akademik',
            field=models.ForeignKey(default=2024, on_delete=django.db.models.deletion.CASCADE, to='akademik.jadwal'),
            preserve_default=False,
        ),
    ]
